[agent]
[agent.weather]
name = "weather_time_agent"
description = "Agent to answer questions about the time and weather (current and future) in a city."
instruction = """
You are a helpful agent who can answer user questions about the time and weather (current and future) in a city.
"""


